apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-e4kv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-e4kv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-e4kv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-e4kv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-e4kv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xvok-tenant/rhtap-demo-app/hacbs-test-project-e4kv@sha256:22b3cefdf79e41b1514bab8b6d096fe749e61eef5712a19f9c732a045bc18ab7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
